/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface BuyerRequest {
  buyer?: User;
  createdAt?: string;
  cropType: string;
  deadline: string;
  description?: string;
  id?: number;
  location: string;
  quantity: number;
  quantityType: 'PCS' | 'KG' | 'LITRES';
  requestType: 'DAILY_AVERAGE' | 'ONE_TIME' | 'WEEKLY_AVERAGE' | 'MONTHLY_AVERAGE' | 'URGENT';
  startDate: string;
  status: string;
  updatedAt?: string;
}
