/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Farmer } from '../models/farmer';
export interface Certification {
  certificationDate?: string;
  certificationType?: 'ORGANIC' | 'SUSTAINABLE' | 'QUALITY_GUARANTEED';
  expiryDate?: string;
  farmer?: Farmer;
  id?: number;
  remarks?: string;
  status?: 'ACTIVE' | 'EXPIRED' | 'PENDING';
}
