/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../../models/role';
export interface Farmer {
  active?: boolean;
  address: string;
  email?: string;
  id?: number;
  name: string;
  password: string;
  phone?: string;
  roles?: Array<Role>;
  status?: 'ACTIVE' | 'INACTIVE';
}
