/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Farmer } from '../models/farmer';
export interface FarmerCultivation {
  cropType?: string;
  cultivationDate?: string;
  description?: string;
  expectedYield?: string;
  farmer?: Farmer;
  harvestDate?: string;
  id?: number;
  landSize?: string;
  location?: string;
  methodOfCultivation?: 'ORGANIC' | 'CONVENTIONAL';
}
