/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FarmerCultivation } from '../models/farmer-cultivation';
import { User } from '../models/user';
export interface FarmerListing {
  availableDateFrom?: string;
  cropType?: string;
  cultivation?: FarmerCultivation;
  description?: string;
  farmer?: User;
  id?: number;
  location?: string;
  quantity?: number;
  status?: 'AVAILABLE' | 'SOLD' | 'PENDING';
}
