/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BuyerRequest } from '../../models/buyer-request';

export interface AddBuyerRequest$Params {
      body: BuyerRequest
}

export function addBuyerRequest(http: HttpClient, rootUrl: string, params: AddBuyerRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<BuyerRequest>> {
  const rb = new RequestBuilder(rootUrl, addBuyerRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BuyerRequest>;
    })
  );
}

addBuyerRequest.PATH = '/api/marketplace/buyer/requests';
