/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FarmerListing } from '../../models/farmer-listing';

export interface FindMatches$Params {
  cropType: string;
}

export function findMatches(http: HttpClient, rootUrl: string, params: FindMatches$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FarmerListing>>> {
  const rb = new RequestBuilder(rootUrl, findMatches.PATH, 'get');
  if (params) {
    rb.path('cropType', params.cropType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FarmerListing>>;
    })
  );
}

findMatches.PATH = '/api/marketplace/match/{cropType}';
