/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Certification } from '../../models/certification';

export interface CertifyFarmer$Params {
  farmerId: number;
  certificationType: string;
  remarks: string;
}

export function certifyFarmer(http: HttpClient, rootUrl: string, params: CertifyFarmer$Params, context?: HttpContext): Observable<StrictHttpResponse<Certification>> {
  const rb = new RequestBuilder(rootUrl, certifyFarmer.PATH, 'post');
  if (params) {
    rb.path('farmerId', params.farmerId, {});
    rb.query('certificationType', params.certificationType, {});
    rb.query('remarks', params.remarks, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Certification>;
    })
  );
}

certifyFarmer.PATH = '/api/certifications/certify/{farmerId}';
